services:
  backend:
    build:
      context: ../components/backend
      dockerfile: ../../docker/backend.dockerfile
      target: backend
    networks:
      - back-tier

  website:
    build:
      context: ../components/website
      dockerfile: ../../docker/website.dockerfile
    networks:
      - front-tier
      - back-tier

  http-balancer:
    build:
      context: ../components/http-balancer
      dockerfile: ../../docker/http-balancer.dockerfile
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - front-tier
    ports:
      - 80:80
      - 443:443
