// source: schedule/v1/model/event.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var common_types_time_pb = require('../../../common/types/time_pb.js');
goog.object.extend(proto, common_types_time_pb);
var common_types_uuid_pb = require('../../../common/types/uuid_pb.js');
goog.object.extend(proto, common_types_uuid_pb);
goog.exportSymbol('proto.schedule.CreateEventRequest', null, global);
goog.exportSymbol('proto.schedule.CreateEventResponse', null, global);
goog.exportSymbol('proto.schedule.Event', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.schedule.Event = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.schedule.Event, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.schedule.Event.displayName = 'proto.schedule.Event';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.schedule.CreateEventRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.schedule.CreateEventRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.schedule.CreateEventRequest.displayName = 'proto.schedule.CreateEventRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.schedule.CreateEventResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.schedule.CreateEventResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.schedule.CreateEventResponse.displayName = 'proto.schedule.CreateEventResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.schedule.Event.prototype.toObject = function(opt_includeInstance) {
  return proto.schedule.Event.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.schedule.Event} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.schedule.Event.toObject = function(includeInstance, msg) {
  var f, obj = {
uuid: (f = msg.getUuid()) && common_types_uuid_pb.Uuid.toObject(includeInstance, f),
timeBegin: (f = msg.getTimeBegin()) && common_types_time_pb.Timestamp.toObject(includeInstance, f),
timeEnd: (f = msg.getTimeEnd()) && common_types_time_pb.Timestamp.toObject(includeInstance, f),
productUuid: (f = msg.getProductUuid()) && common_types_uuid_pb.Uuid.toObject(includeInstance, f),
instructorUuid: (f = msg.getInstructorUuid()) && common_types_uuid_pb.Uuid.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.schedule.Event}
 */
proto.schedule.Event.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.schedule.Event;
  return proto.schedule.Event.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.schedule.Event} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.schedule.Event}
 */
proto.schedule.Event.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new common_types_uuid_pb.Uuid;
      reader.readMessage(value,common_types_uuid_pb.Uuid.deserializeBinaryFromReader);
      msg.setUuid(value);
      break;
    case 2:
      var value = new common_types_time_pb.Timestamp;
      reader.readMessage(value,common_types_time_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTimeBegin(value);
      break;
    case 3:
      var value = new common_types_time_pb.Timestamp;
      reader.readMessage(value,common_types_time_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTimeEnd(value);
      break;
    case 4:
      var value = new common_types_uuid_pb.Uuid;
      reader.readMessage(value,common_types_uuid_pb.Uuid.deserializeBinaryFromReader);
      msg.setProductUuid(value);
      break;
    case 5:
      var value = new common_types_uuid_pb.Uuid;
      reader.readMessage(value,common_types_uuid_pb.Uuid.deserializeBinaryFromReader);
      msg.setInstructorUuid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.schedule.Event.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.schedule.Event.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.schedule.Event} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.schedule.Event.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUuid();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      common_types_uuid_pb.Uuid.serializeBinaryToWriter
    );
  }
  f = message.getTimeBegin();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      common_types_time_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getTimeEnd();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      common_types_time_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getProductUuid();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      common_types_uuid_pb.Uuid.serializeBinaryToWriter
    );
  }
  f = message.getInstructorUuid();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      common_types_uuid_pb.Uuid.serializeBinaryToWriter
    );
  }
};


/**
 * optional common.types.Uuid uuid = 1;
 * @return {?proto.common.types.Uuid}
 */
proto.schedule.Event.prototype.getUuid = function() {
  return /** @type{?proto.common.types.Uuid} */ (
    jspb.Message.getWrapperField(this, common_types_uuid_pb.Uuid, 1));
};


/**
 * @param {?proto.common.types.Uuid|undefined} value
 * @return {!proto.schedule.Event} returns this
*/
proto.schedule.Event.prototype.setUuid = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.schedule.Event} returns this
 */
proto.schedule.Event.prototype.clearUuid = function() {
  return this.setUuid(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.schedule.Event.prototype.hasUuid = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional common.types.Timestamp time_begin = 2;
 * @return {?proto.common.types.Timestamp}
 */
proto.schedule.Event.prototype.getTimeBegin = function() {
  return /** @type{?proto.common.types.Timestamp} */ (
    jspb.Message.getWrapperField(this, common_types_time_pb.Timestamp, 2));
};


/**
 * @param {?proto.common.types.Timestamp|undefined} value
 * @return {!proto.schedule.Event} returns this
*/
proto.schedule.Event.prototype.setTimeBegin = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.schedule.Event} returns this
 */
proto.schedule.Event.prototype.clearTimeBegin = function() {
  return this.setTimeBegin(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.schedule.Event.prototype.hasTimeBegin = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional common.types.Timestamp time_end = 3;
 * @return {?proto.common.types.Timestamp}
 */
proto.schedule.Event.prototype.getTimeEnd = function() {
  return /** @type{?proto.common.types.Timestamp} */ (
    jspb.Message.getWrapperField(this, common_types_time_pb.Timestamp, 3));
};


/**
 * @param {?proto.common.types.Timestamp|undefined} value
 * @return {!proto.schedule.Event} returns this
*/
proto.schedule.Event.prototype.setTimeEnd = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.schedule.Event} returns this
 */
proto.schedule.Event.prototype.clearTimeEnd = function() {
  return this.setTimeEnd(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.schedule.Event.prototype.hasTimeEnd = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional common.types.Uuid product_uuid = 4;
 * @return {?proto.common.types.Uuid}
 */
proto.schedule.Event.prototype.getProductUuid = function() {
  return /** @type{?proto.common.types.Uuid} */ (
    jspb.Message.getWrapperField(this, common_types_uuid_pb.Uuid, 4));
};


/**
 * @param {?proto.common.types.Uuid|undefined} value
 * @return {!proto.schedule.Event} returns this
*/
proto.schedule.Event.prototype.setProductUuid = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.schedule.Event} returns this
 */
proto.schedule.Event.prototype.clearProductUuid = function() {
  return this.setProductUuid(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.schedule.Event.prototype.hasProductUuid = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional common.types.Uuid instructor_uuid = 5;
 * @return {?proto.common.types.Uuid}
 */
proto.schedule.Event.prototype.getInstructorUuid = function() {
  return /** @type{?proto.common.types.Uuid} */ (
    jspb.Message.getWrapperField(this, common_types_uuid_pb.Uuid, 5));
};


/**
 * @param {?proto.common.types.Uuid|undefined} value
 * @return {!proto.schedule.Event} returns this
*/
proto.schedule.Event.prototype.setInstructorUuid = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.schedule.Event} returns this
 */
proto.schedule.Event.prototype.clearInstructorUuid = function() {
  return this.setInstructorUuid(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.schedule.Event.prototype.hasInstructorUuid = function() {
  return jspb.Message.getField(this, 5) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.schedule.CreateEventRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.schedule.CreateEventRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.schedule.CreateEventRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.schedule.CreateEventRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
timeBegin: (f = msg.getTimeBegin()) && common_types_time_pb.Timestamp.toObject(includeInstance, f),
timeEnd: (f = msg.getTimeEnd()) && common_types_time_pb.Timestamp.toObject(includeInstance, f),
productUuid: (f = msg.getProductUuid()) && common_types_uuid_pb.Uuid.toObject(includeInstance, f),
instructorUuid: (f = msg.getInstructorUuid()) && common_types_uuid_pb.Uuid.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.schedule.CreateEventRequest}
 */
proto.schedule.CreateEventRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.schedule.CreateEventRequest;
  return proto.schedule.CreateEventRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.schedule.CreateEventRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.schedule.CreateEventRequest}
 */
proto.schedule.CreateEventRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = new common_types_time_pb.Timestamp;
      reader.readMessage(value,common_types_time_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTimeBegin(value);
      break;
    case 3:
      var value = new common_types_time_pb.Timestamp;
      reader.readMessage(value,common_types_time_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTimeEnd(value);
      break;
    case 4:
      var value = new common_types_uuid_pb.Uuid;
      reader.readMessage(value,common_types_uuid_pb.Uuid.deserializeBinaryFromReader);
      msg.setProductUuid(value);
      break;
    case 5:
      var value = new common_types_uuid_pb.Uuid;
      reader.readMessage(value,common_types_uuid_pb.Uuid.deserializeBinaryFromReader);
      msg.setInstructorUuid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.schedule.CreateEventRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.schedule.CreateEventRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.schedule.CreateEventRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.schedule.CreateEventRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTimeBegin();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      common_types_time_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getTimeEnd();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      common_types_time_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getProductUuid();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      common_types_uuid_pb.Uuid.serializeBinaryToWriter
    );
  }
  f = message.getInstructorUuid();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      common_types_uuid_pb.Uuid.serializeBinaryToWriter
    );
  }
};


/**
 * optional common.types.Timestamp time_begin = 2;
 * @return {?proto.common.types.Timestamp}
 */
proto.schedule.CreateEventRequest.prototype.getTimeBegin = function() {
  return /** @type{?proto.common.types.Timestamp} */ (
    jspb.Message.getWrapperField(this, common_types_time_pb.Timestamp, 2));
};


/**
 * @param {?proto.common.types.Timestamp|undefined} value
 * @return {!proto.schedule.CreateEventRequest} returns this
*/
proto.schedule.CreateEventRequest.prototype.setTimeBegin = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.schedule.CreateEventRequest} returns this
 */
proto.schedule.CreateEventRequest.prototype.clearTimeBegin = function() {
  return this.setTimeBegin(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.schedule.CreateEventRequest.prototype.hasTimeBegin = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional common.types.Timestamp time_end = 3;
 * @return {?proto.common.types.Timestamp}
 */
proto.schedule.CreateEventRequest.prototype.getTimeEnd = function() {
  return /** @type{?proto.common.types.Timestamp} */ (
    jspb.Message.getWrapperField(this, common_types_time_pb.Timestamp, 3));
};


/**
 * @param {?proto.common.types.Timestamp|undefined} value
 * @return {!proto.schedule.CreateEventRequest} returns this
*/
proto.schedule.CreateEventRequest.prototype.setTimeEnd = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.schedule.CreateEventRequest} returns this
 */
proto.schedule.CreateEventRequest.prototype.clearTimeEnd = function() {
  return this.setTimeEnd(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.schedule.CreateEventRequest.prototype.hasTimeEnd = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional common.types.Uuid product_uuid = 4;
 * @return {?proto.common.types.Uuid}
 */
proto.schedule.CreateEventRequest.prototype.getProductUuid = function() {
  return /** @type{?proto.common.types.Uuid} */ (
    jspb.Message.getWrapperField(this, common_types_uuid_pb.Uuid, 4));
};


/**
 * @param {?proto.common.types.Uuid|undefined} value
 * @return {!proto.schedule.CreateEventRequest} returns this
*/
proto.schedule.CreateEventRequest.prototype.setProductUuid = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.schedule.CreateEventRequest} returns this
 */
proto.schedule.CreateEventRequest.prototype.clearProductUuid = function() {
  return this.setProductUuid(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.schedule.CreateEventRequest.prototype.hasProductUuid = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional common.types.Uuid instructor_uuid = 5;
 * @return {?proto.common.types.Uuid}
 */
proto.schedule.CreateEventRequest.prototype.getInstructorUuid = function() {
  return /** @type{?proto.common.types.Uuid} */ (
    jspb.Message.getWrapperField(this, common_types_uuid_pb.Uuid, 5));
};


/**
 * @param {?proto.common.types.Uuid|undefined} value
 * @return {!proto.schedule.CreateEventRequest} returns this
*/
proto.schedule.CreateEventRequest.prototype.setInstructorUuid = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.schedule.CreateEventRequest} returns this
 */
proto.schedule.CreateEventRequest.prototype.clearInstructorUuid = function() {
  return this.setInstructorUuid(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.schedule.CreateEventRequest.prototype.hasInstructorUuid = function() {
  return jspb.Message.getField(this, 5) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.schedule.CreateEventResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.schedule.CreateEventResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.schedule.CreateEventResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.schedule.CreateEventResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
uuid: (f = msg.getUuid()) && common_types_uuid_pb.Uuid.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.schedule.CreateEventResponse}
 */
proto.schedule.CreateEventResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.schedule.CreateEventResponse;
  return proto.schedule.CreateEventResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.schedule.CreateEventResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.schedule.CreateEventResponse}
 */
proto.schedule.CreateEventResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new common_types_uuid_pb.Uuid;
      reader.readMessage(value,common_types_uuid_pb.Uuid.deserializeBinaryFromReader);
      msg.setUuid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.schedule.CreateEventResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.schedule.CreateEventResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.schedule.CreateEventResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.schedule.CreateEventResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUuid();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      common_types_uuid_pb.Uuid.serializeBinaryToWriter
    );
  }
};


/**
 * optional common.types.Uuid uuid = 1;
 * @return {?proto.common.types.Uuid}
 */
proto.schedule.CreateEventResponse.prototype.getUuid = function() {
  return /** @type{?proto.common.types.Uuid} */ (
    jspb.Message.getWrapperField(this, common_types_uuid_pb.Uuid, 1));
};


/**
 * @param {?proto.common.types.Uuid|undefined} value
 * @return {!proto.schedule.CreateEventResponse} returns this
*/
proto.schedule.CreateEventResponse.prototype.setUuid = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.schedule.CreateEventResponse} returns this
 */
proto.schedule.CreateEventResponse.prototype.clearUuid = function() {
  return this.setUuid(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.schedule.CreateEventResponse.prototype.hasUuid = function() {
  return jspb.Message.getField(this, 1) != null;
};


goog.object.extend(exports, proto.schedule);
